service: social-barometer

custom:
  service: ${self:service}-${self:provider.stage}
  defaultStage: dev
  defaultRegion: eu-west-1
  defaultAccount: 627450054263
  defaultProfile: hackathon
  version: 1

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: hackathon
  stage: dev
  account: 627450054263
  memorySize: 128
  apiKeys:
    - ${self:custom.service}
  timeout: 30
  environment:
    TOKEN: 123739874833009|90f51ceaa1b4968477157d4acb4b256a
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:*:*:table/*"

functions:
  page:
    handler: src/handler.facebook
    events:
     - http:
        path: page/{id}
        integration: lambda-proxy
        method: get
        cors: true
  search:
    handler: src/handler.search
    events:
     - http:
        path: search
        integration: lambda-proxy
        method: get
        cors: true
  instagram:
    handler: src/handler.instagram
    events:
     - http:
        path: instagram/{user}
        integration: lambda-proxy
        method: get
        cors: true        

